# Generated by Django 5.1 on 2024-11-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolink',
            name='status',
        ),
        migrations.RemoveField(
            model_name='videolink',
            name='transcribed_text',
        ),
    ]
