# Generated by Django 5.1 on 2024-12-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolink',
            name='file_path',
            field=models.FilePathField(path='C:\\Users\\ahmed\\Desktop\\wizzeframeworks\\media'),
        ),
        migrations.AlterField(
            model_name='videolink',
            name='thumbnail_path',
            field=models.FilePathField(blank=True, default='', path='C:\\Users\\ahmed\\Desktop\\wizzeframeworks\\media'),
        ),
    ]
